route:
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: test-receiver

receivers:
  - name: test-receiver
    webhook_configs:
      - url: http://rcvr:9595/
