services:
  prometheus:
    image: prom/prometheus:v2.37.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    profiles: ["obs"]

  grafana:
    image: grafana/grafana:9.0.0
    container_name: grafana
    environment:
      # Username: admin, Password: admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH="/var/lib/grafana/dashboards/"
    volumes:
      - ./grafana-config/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana-config/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana-config/dashboard.json:/var/lib/grafana/dashboards/prometheus-stats/dashboard.json
      - ./grafana-config/demo-service-dashboard.json:/var/lib/grafana/dashboards/prometheus-stats/demo-service-dashboard.json
      - ./grafana-config/web-application-dashboard.json:/var/lib/grafana/dashboards/prometheus-stats/web-application-dashboard.json
    ports:
      - "3001:3000"
    profiles: ["obs"]

  skynet-app:
    container_name: skynet-app
    build:
      context: ./../../skynet-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    profiles: ["apps", "skynet"]

  lf-app-1:
    container_name: lf-app-1
    build:
      context: ./../../../lf-app/demo-service-source
      dockerfile: Dockerfile
    ports:
      - "8002:8080"
    profiles: ["apps", "lf"]

  lf-app-2:
    container_name: lf-app-2
    build:
      context: ./../../../lf-app/demo-service-source
      dockerfile: Dockerfile
    ports:
      - "8003:8080"
    profiles: ["apps", "lf"]

  lf-app-3:
    container_name: lf-app-3
    build:
      context: ./../../../lf-app/demo-service-source
      dockerfile: Dockerfile
    ports:
      - "8004:8080"
    profiles: ["apps", "lf"]
  
  lf-app-instrumented-go:
    container_name: lf-app-instrumented-go
    build:
      context: ./../../../lf-app/instrumentation-exercise/go
      dockerfile: Dockerfile
    ports:
     - "8005:12345"
    profiles: ["apps", "lf"]

  lf-app-instrumented-python:
    container_name: lf-app-instrumented-python
    build:
      context: ./../../../lf-app/instrumentation-exercise/python
      dockerfile: Dockerfile
    ports:
     - "8006:12345"
    profiles: ["apps", "lf"]
  
  mysql:
    image: mysql:8.0-bookworm
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=psw123
    volumes:
     - ./mysql-config/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "8007:3306"
    profiles: ["db", "mysql"]

  mysql-exporter:
    image: prom/mysqld-exporter:v0.18.0
    depends_on:
      - mysql
    container_name: mysql-exporter
    command:
      - --config.my-cnf=/cfg/config.my-cnf
    ports:
      - "8008:9104"
    volumes:
      - ./mysql-config/mysql-exporter.cnf:/cfg/config.my-cnf
    profiles: ["db", "mysql"]

  
  psql:
    image: postgres:15
    container_name: psql
    ports:
      - "8009:5432"
    environment:
      POSTGRES_PASSWORD: psw123
    volumes:
      - ./psql-config/init.sql:/docker-entrypoint-initdb.d/init.sql
    profiles: ["db", "psql"]
  
  psql-exporter:
    image:  quay.io/prometheuscommunity/postgres-exporter:v0.17.1
    container_name: psql-exporter
    depends_on:
     - psql
    ports:
      - "8010:9187"
    environment:
      - DATA_SOURCE_URI="psql:5432/postgres?sslmode=disable"
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=psw123
    volumes:
      - ./psql-config/postgres_exporter.yml:/cnf/postgres_exporter.yml
    command:
     - --config.file=/cnf/postgres_exporter.yml
    profiles: ["db", "psql"]
    
  cpu-exporter:
    container_name: cpu-exporter
    build:
      context: ./../../../cpu-exporter/
      dockerfile: Dockerfile
    ports:
      - "8011:8000"
    profiles: ["exporter"]
    

  node-exporter:
    image: docker.io/prom/node-exporter:v1.9.1
    container_name: node-exporter
    command:
      - --path.rootfs=/host
    pid: host
    volumes:
      - /:/host:ro # rslave you can add rslave if you want to see volume mounts after the container started. Probably because of wsl this can cause some issue on my personal laptop
    ports:
      - "8015:9100"
    profiles: ["system"]
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.52.1
    container_name: cadvisor
    hostname: cadvisor
    restart: unless-stopped
    ports:
      - "8016:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro 
    profiles: ["system"]
